### ISSUE TITLE
Fix punctuation in index

### ISSUE THREAD

**Issue by connoryork** [ajb2969/InformationRetrieval#19]
remove - and " from index, etc

**Comment by connoryork** [comment]
Sort of related: should queries be stripped of punctation since our index is punctuation free?

**Comment by ajb2969** [comment]
The issue with removing punctuation from queries is then you end up with theres instead of there's, neither of which are contained in the index. If queries are to be stripped of punctuation then there should be a limited or finite set of punctuation removed that doesn't affect the query itself

**Comment by ajb2969** [comment]
This issue will be closed due to punctuation being removed using the java punctuation regex in the index
