### ISSUE TITLE
Figure out hosting

### ISSUE THREAD

**Issue by connoryork** [ajb2969/InformationRetrieval#23]

**Comment by ajb2969** [comment]
Speed has been noted as an issue. After discussion with the professor, we will decide how to move forward with hosting

**Comment by ajb2969** [comment]
after discussion, found out we can host on the cs machines. Will update after code has been uploaded

**Comment by ajb2969** [comment]
issues with port forwarding on cs machine. Was able to host on Heroku instead, also allows for better build and deployment process
